code_examples/python/django_example/books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    # /books/
    path('', views.BooksModelView.as_view(), name='index'),

    # /books/book
    path('book/', views.BookList.as_view(), name='book_list'),

    # /books/author/
    path('author/', views.AuthorList.as_view(), name='author_list'),

    # /books/publisher/
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),

    # /books/book/99/
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),

    # /books/author/99/
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),

    # /books/publisher/99/
    path('publisher/<int:pk>', views.PublisherDetail.as_view(), name='publisher_detail'),
]

code_examples/python/django_example/ch5/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('books/', include('books.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

code_examples/python/django_example/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

""" Function-based views """
urlpatterns = [
    path('', views.index, name='index'), # /polls/
    path('<int:question_id>/', views.detail, name='detail'), # /polls/<int>
    path('<int:question_id>/results/', views.results, name='results'), # /polls/<int>/results/
    path('<int:question_id>/vote/', views.vote, name='vote'), # /polls/<int>/vote/
]

""" Class-based views """
urlpatterns2 = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

code_examples/python/django_example/books/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    publication_date = models.DateField()

    def __str__(self):
        return self.title

class Author(models.Model):
    name = models.CharField(max_length=50)
    salutation = models.CharField(max_length=100)
    email = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name

code_examples/python/django_example/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

code_examples/python/django_example/books/views.py
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from django.shortcuts import render

from .models import Book, Author, Publisher

# Create your views here.

# TemplateView
class BooksModelView(TemplateView):
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_list'] = ['Book', 'Author', 'Publisher']
        return context

# ListView
class BookList(ListView):
    """Default variables of ListView
    context[object_list] = Book.objects.all()
    template_name = 'book_list.html'
    """
    model = Book

class AuthorList(ListView):
    model = Author

class PublisherList(ListView):
    model = Publisher

# DetailView
class BookDetail(DetailView):
    """Default variables of DetailView
    context[object] = Book.objects.get(pk=(parameter passed from URLconf))
    template_name = 'book_detail.html'
    """
    model = Book

class AuthorDetail(DetailView):
    model = Author

class PublisherDetail(DetailView):
    model = Publisher

code_examples/python/django_example/ch5/views.py
from django.views.generic.base import TemplateView
from django.apps import apps

# TemplateView
class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['app_list'] = ['books']
        dictVerbose = {} # No need to hard-code app's names
        for app in apps.get_app_configs():
            """
            apps.get_app_configs() returns a list of Configs added to INSTALLED_APPS in settings.py.
            """
            if 'site-packages' not in app.path: # if the app is not an externerl app
                """
                app.path is an actual path of each app. 'site-packages' means external library app.
                """
                dictVerbose[app.label] = app.verbose_name
                """
                verbose_name is defiend in each app's apps.py.
                (app.label = 'books', app.verbose_name = 'Book-Author-Publisher App')
                """
        context['verbose_dict'] = dictVerbose
        return context

code_examples/python/django_example/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from .models import Question, Choice

# pylint: disable=no-member

# Create your views here.
def index(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5] # Get 5 latest questions
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id) # Question.objects.get(pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'question': question, 'error_message': "You didn't select a choice."})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


from django.views import generic

# Class-based GenericView
class IndexView(generic.ListView):
    template_name = 'polls/index.html' # If not explicitely specifed, default is 'polls/question_list.html'
    context_object_name = 'latest_question_list' # default is 'object_list' or 'question_list'
    
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html' # default is 'polls/question_detail.html', object is 'object' or 'question'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html' # deafult is 'polls/question_detail.html'

code_examples/python/django_example/books/templates/base_books.html
{% extends "base.html" %}

<title>{% block title %}Books Application Site{% endblock %}</title>

{% block sidebar %}
{{ block.super }} <!-- Use sidebar block in base.html -->
<ul>
    <li><a href="/books/">Books_Home</a></li>
</ul>
{% endblock %}

code_examples/python/django_example/books/templates/books/author_detail.html
{% extends "base_books.html" %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>{{ object.salutation }}</p>
<li>Email: {{ object.email }}</li>
<br>
<p>Books</p>
{% for book in object.book_set.all %}
    <li><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a></li>
{% endfor %}
{% endblock content %}

code_examples/python/django_example/books/templates/books/author_list.html
{% extends "base_books.html" %}

{% block content %}
<h2>Author List</h2>
<ul>
    {% for author in object_list %}
        <li><a href="{% url 'books:author_detail' author.id %}">{{ author.name }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

code_examples/python/django_example/books/templates/books/book_detail.html
{% extends "base_books.html" %}

{% block content %}
<h1>{{ object.title }}</h1>
<br>
<li>Authors:
{% for author in object.authors.all %}
<!-- A Book class' variable authors is ManyToManyField -->
    <a href="{% url 'books:author_detail' author.id %}">{{ author }}</a>
    {% if not forloop.last %}
    <!-- if more than 2 authors -->
        ,
    {% else %}
    {% endif %}
{% endfor %}
</li>
<li>Publisher: <a href="{% url 'books:publisher_detail' object.id %}">{{ object.publisher }}</a></li>
<li>Publication date: {{ object.publication_date }}</li>
{% endblock content %}

code_examples/python/django_example/books/templates/books/book_list.html
{% extends "base_books.html" %}

{% block content %}
<h2>Book List</h2>
<ul>
    {% for book in object_list %}
        <li><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

code_examples/python/django_example/books/templates/books/index.html
{% extends "base_books.html" %}

{% block content %}
<h2>Books Management System</h2>
<ul>
    {% for model_name in model_list %}
    <!-- context['model_list'] = ['Book', 'Author', 'Publisher'] -->
        {% with "books:"|add:model_name|lower|add:"_list" as urlvar %}
        <!-- If model_name is Book, urlvar is books:book_list -->
            <li><a href="{% url urlvar %}">{{ model_name }}</a></li>
        {% endwith %}
    {% endfor %}
</ul>
{% endblock content %}

code_examples/python/django_example/books/templates/books/publisher_detail.html
{% extends "base_books.html" %}

{% block content %}
<h1>{{ object.name }}</h1>
<p><a href="{{ object.website }}">{{ object.website }}</a></p>
<li>Address: {{ object.address }}</li>
<br>
<p>Published Books</p>
{% for book in object.book_set.all %}
    <li><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a></li>
{% endfor %}
{% endblock content %}

code_examples/python/django_example/books/templates/books/publisher_list.html
{% extends "base_books.html" %}

{% block content %}
<h2>Publisher List</h2>
<ul>
    {% for publisher in object_list %}
        <li><a href="{% url 'books:publisher_detail' publisher.id %}">{{ publisher.name }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

code_examples/python/django_example/polls/templates/base_polls.html
{% extends "base.html" %}

<title>{% block title %}Polls Application Stie{% endblock %}</title>

{% block sidebar %}
{{ block.super }}
<ul>
    <li><a href="/polls/">Polls_Home</a></li>
</ul>
{% endblock %}

code_examples/python/django_example/polls/templates/polls/detail.html
{% extends "base_polls.html" %}

{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="POST">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    <br>
{% endfor %}
<input type="submit" value="Vote">
</form>

{% endblock content %}

code_examples/python/django_example/polls/templates/polls/index.html
{% extends "base_polls.html" %}

{% block content %}

<h2>Polls Question List</h2>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock content %}

code_examples/python/django_example/polls/templates/polls/results.html
{% extends "base_polls.html" %}

{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes| }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock content %}

code_examples/python/django_example/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}" />
    <title>{% block title %}Chapter 5{% endblock %}</title>
</head>
<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Project_Home</a></li>
            <li><a href="/admin/">Admin</a></li>
        </ul>
        {% endblock %}
        <br>
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>    
</html>

code_examples/python/django_example/templates/home.html
{% extends "base.html" %}

{% block content %}
<h2>Django Applications</h2>

<!-- with a line "context['app_list'] = ['books']" in views.py -->
<ul>
    {% for app_name in app_list %}
        {% with app_name|add:":"|add:"index" as urlvar %}
        <!-- books:index -->
            <li><a href="{% url urlvar %}">{{ app_name }}</a></li>
        {% endwith %}
    {% endfor %}
</ul>

<!-- with "context['verbose_dict'] = dictVerbose" in views.py -->
<ul>
    {% for key, value in verbose_dict.items %}
        <li><a href="{% url key|add:':index' %}">{{ key }}: {{ value }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}